
* 第 11 章 字符串和字符串函数

** 表示字符串和字符串 I/O
*** COMMENT 在程序中定义字符串
    字符串定义方式
    1. 字符串字面量(字符串常量)
       用双引号括起来的内容成本为字符串字面量(string literal), 也叫做字符串常量
       (string constant). 双引号中的字符串和编译器自动加入末尾的 ~\0~ 字符, 都作
       为字符串储存在内容中, 所以 ~"I am a symbolic string constant"~, ~"I am a
       string in an array."~, ~"Something is pointed at me."~, ~"Here are
       some strings:"~ 都是字符串字面量.

       从 ANSI C 标准起, 如果字符串字面量之间没有间隔, 或者空白字符分割, C 会将其
       视为串联起来的字符串字面量, 例如:
       #+begin_src c
         char greeting[50] = "Hello, and "" how are" "you"
             " today!";
         // 与下面代码等价:
         char greeting[50] = "Hello, and how are you today!";
       #+end_src
       如果要在字符串内部使用双引号, 必须转义

       字符串常量属于静态存储类别(static storage class), 这说明在函数中使用字符
       串常量, 该字符串只会被储存一次, 在整个程序的生命期内存在, 即使函数被调用
       多次. 用双引号括起来的内容被视为指向该字符串储存位置的指针. 这类似于把数
       组名作为指向该数组位置的指针.

    2. 字符串数组和初始化
       定义字符串数组时, 必须让编译器知道需要多少空间. 一种方法是用足够空间的数
       组储存字符串. 
       #+begin_src c
         const char m1[40] = "Limit yourself to one line's worth.";
       #+end_src
       ~const~ 表名不会更改这个字符串

       这种形式的初始化比标准的数组初始化形式简单的多:
       #+begin_src c
         const char m1[40] = { 'L', 'i', 'm', 'i', 't', '', 'y', 'o', 'u', 'r', 's', 'e', 'l', 'l'
                               , 'f', '', 't', 'o', '', 'o', 'n', 'e', '', 'l', 'i', 'n', 'e', '\',
                               , 's', ' ', 'w', 'o', 'r', 't', 'h', '.', '\0'};
       #+end_src

       *注意最后的空字符*, 没有这个空字符, 就是一个字符数组而不是一个字符串

       在指定数组大小时, 要确保数组的元素个数至少比字符串长度 *多 1* (为了容纳空
       字符). 所有未被使用的元素都被自动初始化为 0

       通常, 让编译器确定数组的大小很方便且合理. 因为处理字符串的函数通常不知道
       数组的大小, 这些函数通过查找字符串末尾的空字符来确定字符串在何处结束

       让编译器计算数组大小只能用在 *初始化* 时. 如果创建一个稍后再填充的数组,
       就必须在声明时指定大小.

       字符数组名和其他数组名一样, 是该数组首元素的地址. 因此, 假设有如下代码:
       #+begin_src c
         char car[10] = "Tata";
       #+end_src

       以下表达式为 '真':
       #+begin_src c
         car == &car[0];
         *car == 'T';
         *(car + 1) == car[1] == 'a';
       #+end_src

       还可以用 *指针表示法* 创建字符串:
       #+begin_src c
         const char* pt1 = "Something is pointing at me";
       #+end_src
       该声明与下面的声明几乎相同:
       #+begin_src c
         const char ar1[] = "Something is pointing at me";
       #+end_src
       以上 2 个声明表名, ~pt1~ 和 ~ar1~ 都是该字符串的地址. 尽管如此, 这两种形式
       *并不完全相同*

    3. 数组和指针
       - 数组形式(~ar[n]~): 在计算机的内存中分配一个内含 n 个元素的数组(每个元素对
         应一个字符, 还加上一个末尾的空字符 ~'\0'~), 每个元素被初始化为字符串字
         面量对应的字符. 冗长, 字符串都作为可执行文件的一部分储存在数据段中. 当
         把程序载入内存时, 也载入了程序中的字符串. 字符串储存在静态存储区(static
         memory)中. 但是, 程序在 *开始运行时才会为该数组分配内存*. 此时, 才将字
         符串拷贝到数组中.
         *注意*: 此时字符串有 2 个副本, 一个是静态内存中的字符串字面量, 一个是储存
         在 ~ar~ 数组中的字符串

         此后, 编译器便吧数组名 ~ar~ 识别为该数组首元素地址(~&ar[0]~)的别名. 这
         里关键要理解, 在数组形式中, ~ar~ 是地址常量, *不能更改* ~ar~, 如果改变了
         ~ar~, 则意味着改变了数组的存储位置(即地址). 可以进行类似 ~ar + 1~ 这样
         的操作, 标识数组的下一个元素. 但是 *不允许进行 ~++ar~ 这样的操作*.

       - 指针形式(~*pt1~): 也使得编译器为字符串在静态储存区预留相应元素的空间. 另
         外, 一旦开始执行程序, 它会为指针变量 ~pt1~ 流出一个存储位置, 并把字符串
         的地址储存在指针变量中. 该变量最初指向该字符串的首字符, 但是它的值可以
         改变. 因此, *可以使用* 递增运算符. 例如: ~++pt1~ 将指向第 2 个字符

         字符串字面量被视为 ~const~ 数组. 由于 ~pt1~ 指向这个数据, 所以应该把
         ~pt1~ 声明为指向 ~const~ 数组的指针. 这意味着不能用 ~pt1~ 改变它所指向
         的数据, 但是仍然可以改变 ~pt1~ 的值.

         *初始化数组把静态存储区的字符串拷贝到数组中, 而初始化指针只把字符串的地
         址拷贝给指针*

    4. 数组和指针的区别
       - 数组名是 *常量*: 数组名不可再次赋值

       - 指针名是 *变量*: 只有指针可以进行递增操作
         
         const 限定符的指针初始化:
         #+begin_src c
           char* word = "frame";

           word[1] = 'l';
         #+end_src
         编译器 *可能允许* 这样做, 但是对当前的 C 标准而言, 这样的行为是未定义的,
         这样的语句可能导致内存访问错误. 
         原因: 编译器可以使用内存中的一个副本来表示所有完全相同的字符串字面量

         *建议*: 在把指针初始化为字符串字面量时使用 const 限定符
         
         把非 const 数组初始化为字符串字面量缺不会导致类似的问题. 因为数组获得的
         是原始字符串的 *副本*

       - 字符串数组
         指针数组效率高但不可修改, 而多维数组中内容可以修改

*** 指针和字符串 
    拷贝地址比拷贝整个字符串(数组)高效

** 字符串输入
*** 分配空间
    假设编写了如下代码:
    #+begin_src c
      char* name;
      scanf("%s", name);
    #+end_src
    虽然可能通过编译(警告), 但是在读入 ~name~ 时, ~name~ 可能会擦写掉程序中的数
    据或代码, 从而导致程序异常终止. 因为 ~scanf()~ 要把信息拷贝至参数指定的地址
    上, 而此时该参数是个未初始化的指针, ~name~ 可能会指向任何地方.

*** 不幸的 ~gets()~ 函数
    ~gets()~ 函数简单易用, 读取整行输入, 直至遇到换行符, 然后丢弃换行符, 储存其
    余字符, 并在这些字符的末尾添加一个空字符使其成为一个 C 字符串. 经常和
    ~puts()~ 配对使用, 该函数用于显示字符串, 并在末尾添加换行符.

    *警告*: ~gets()~ 的唯一参数 *无法检查数组是否装得下输入行*, 数组名会被转换成
     该数组首元素的地址, 因此, ~gets()~ 只知道数组的开始处, 并不知道数组中有多少
     个元素

     如果输入的字符串过长, 会导致 *缓冲区溢出(buffer overflow)*. 即多余的字符超
     出了指定的目标空间. 如果这些多余的字符只是占用了尚未使用的内存, 就不会立即
     出现问题; 如果他们擦写掉程序中的其他数据, 会导致程序异常中止; 或者还有其他
     情况

     C11 标准 *废除* 了 ~gets()~ 函数

*** ~gets()~ 的替代品
    过去通常使用 ~fgets()~ 来替代 ~gets()~. C11 标准新增的 ~gets_s()~ 函数也可以
    代替 ~gets()~. 但是它是 ~stdio.h~ 输入/输出函数系列的 *可选* 扩展, 所以支持
    C11 的编译器也不一定支持它

    1. ~fgets()~ 函数(和 ~fputs()~)
       ~fgets()~ 函数通过第二个参数限制读入字符数来解决移除的问题. 该函数专门设
       计用于处理文件输入, 所以一般情况下可能不太好用. 与 ~gets()~ 的区别:
       - ~fgets()~ 函数的第 2 个参数指明了读入字符的最大数量. 如果该参数的值是 n,
         那么 ~fgets()~ 将读入 n-1 个字符, 或者读到遇到的第一个换行符位置
       - 如果 ~fgets()~ 读到一个换行符, 会把它存储在字符串中. 这点与 ~gets()~ 不
         同, ~gets()~ 会丢弃换行符
       - ~fgets()~ 函数的第 3 个参数指明要读入的文件. 如果读入从键盘输入的数据, 则
         以 stdin(标准输入作为参数), 该标识符定义在 ~stdio.h~ 中
       - 因为 ~fgets()~ 函数把换行符放在字符串的末尾(假设输入行不溢出), 通常要与
         ~fputs()~ 函数(和 ~puts()~ 类似) 配对使用, 除非该函数不再字符串末尾添加
         换行符. ~fputs()~ 函数的第 2 个参数指明它要写入的文件. 如果要显示在计算机
         显示器上, 应使用 stdout(标准输出) 作为该参数
       - ~fputs()~ 函数 *不会在字符串末尾添加一个换行符*, ~fputs()~ 函数返回指向
         char 的指针. 如果一切进行顺利, 该函数返回的地址与传入的第一个参数相同.
         如果函数读到文件结尾, 它将返回一个特殊的指针: 空指针 (null pointer). 该
         指针保证不会指向有效的数据, 代码中可以用数字 0 来代替, 不过在 C 语言中用
         宏 ~NULL~ 来代替更常见(如果读入错误, 也返回 ~NULL~)

         系统使用缓冲的 I/O, 这意味着用于按下 ~Return~ 键之前, 输入都被存储在临
         时存储区(即, 缓冲区) 中. 按下 ~Return~ 键就在输入中增加了一个换行符, 并
         把整行输入发送给 ~fgets()~. 对于输出, ~fputs()~ 把字符发送给另一个缓冲
         区, 当发送换行符时, 缓冲区的内容被发送至屏幕上
       - 空字符和空指针:
         + 空字符(或 ~'\0'~): 是用于标记 C 字符串末尾的字符, 其对应编码是 0, 由
           于其他字符的编码不可能是 0, 所以不可能是字符串的一部分
           空字符是 *整数类型*, 空字符是一个字符, 占 1 字节

         + 空指针(或 ~NULL~)有一个值, 该值不会与任何数据的有效地址对应. 通常, 函
           数使用它返回一个有效地址表示某些特殊情况发生, 例如遇到文件结尾或未能
           按预期执行
           空指针是 *指针类型*, 空指针是一个地址, 通过占 4 字节

    2. ~gets_s~ 函数
       C11 新增的 ~gets_s()~ 函数(可选)和 ~fgets()~ 类似, 用一个参数限制读入的空
       字符数. 
       与 ~fgets()~ 区别:
       1) ~gets()~ 只总从标准输入中读取数据, 所以不需要第三个参数

       2) 如果 ~gets_s()~ 读取到换行符, 会丢弃它而不是存储它

       3) 如果 ~gets_s()~ 读到最大字符数都没有读到换行符, 会执行以下几步:
          1. 把模板数组中的首字符设置为空字符

          2. 读取并丢弃随后输入直至读到换仿佛或文件结尾, 然后返回空指针

          3. 调用依赖实现的 "处理函数", 可能会中止会退出程序

             只要输入行未超过最大字符数, 效果与 ~gets()~ 几乎一致
             当输入与预期不符时, ~fgets()~ 比 ~gets_s()~ 更方便

    3. ~s_gets()~ 函数
       
       #+begin_src c
         char* s_gets(char* st, int n)
         {
           char* ret_val;
           int i = 0;

           ret_val = fgets(st, n, stdin);

           if (ret_val) // 即 判断是否为 NULL
           {

             while (st[i] != '\n' && st[i] != '\0') {
               ++i;
             }

             // 使用空字符替换换行符
             if (st[i] == '\n') {
               st[i] = '\0';      
             } else {
               while (getchar() != '\n') {
                 continue;
               }
             }
           }

           return ret_val;
         }
       #+end_src

       如果 ~fgets()~ 返回 ~NULL~ 说明读到文件结尾或出现读取错误, 跳过该过程, 如
       果出现换行符, 使用空字符替换. 若出现空字符, 丢弃该输入行的其余字符, 返回
       与 ~fgets()~ 相同的值

       输入行多出来的字符会被留在缓冲区中, 成为下一次读取语句的输入. 若类型不匹
       配可能导致程序崩溃
*** ~scanf()~ 函数
    ~scanf()~ 和 ~gets()~ 或 ~fgets()~ 的区别在于它们如何确定字符串的末尾

    ~scanf()~ 更像是 "获取单词" 函数, 而不是 "获取字符串" 函数; 如果预留的存储区
    装的下行, ~gets()~ 和 ~fgets()~ 会读取第一个换行符之前所有的字符.
    
    ~scanf()~ 函数有 2 种方法确定输入结束. 无论哪种方法, 都从第一个非空白字符作为
    字符串的开始. 如果使用 ~%s~ 转换说明, 以下一个空白字符(空行, 空格, 制表符或
    换行符)作为字符串的结束(字符串不包括空白字符). 如果指定了字段宽度, 如
    ~%10s~, 那么 ~scanf()~ 将读取 10 个字符或读到第一个空白字符停止(先满足的条件
    即是输入结束的条件):

    | 输入语句            | 原输入序列*  | name 中的内容 | 剩余输入序列 |
    |---------------------+--------------+--------------+--------------|
    | scanf("%s" name);   | Fleebert Hup | Fleebert     | Hup          |
    | scanf("%5s", name); | Fleebert Hup | Fleeb        | ert Hup      |
    | scanf("%5s", name); | Ann Ular     | Ann          | Ular         |

    
    当第一个参数长度过长时, 再次使用 ~scanf()~ 赋值时会从上一次调用结束的地方继
    续读取数据

    根据输入数据的性质, 用 ~fgets()~ 读取从键盘输入的数据更合适. 例如, ~scanf()~
    无法完整读取书名或歌曲名, 除非这些名称是一个单词. ~scanf()~ 的典型用法是读取
    并转换混合数据为某种标准形式. 例如, 如果输入行包含一种工具名, 库存量和单价,
    就可以使用 ~scanf()~. 否则可能要自己拼凑一个函数处理一些输入检查. 如果一次只
    输入一个单词, 用 ~scanf()~ 也没问题.

    ~scanf()~ 和 ~gets()~ 类似, 也存在溢出可能, 转换说明指名字段宽度可以防止溢出
** 字符串输出
   C 有 3 个标准库函数用于打印字符串: ~puts()~, ~fputs()~ 和 ~printf()~

*** ~puts()~ 函数
    该函数仅需把字符串的地址作为参数传递即可

    每个字符串单独占一行, 因为 ~puts()~ 在显示字符串时会自动在其末尾添加一个换行
    符.

    该函数遇到空字符时就停止输出, 所以 *必须确保有空字符*

    没有空字符结果会由编译器不同而输出内容不同, ~puts()~ 会在一个空字符下停止

*** ~fputs()~ 函数
    ~fputs()~ 函数是 ~puts()~ 针对文件定制的版本. 区别如下:
    ~fputs()~ 函数的第二个参数指名要写入数据的文件, 如果要打印在显示器上, 可以用
    定义在 ~stdio.h~ 中的 ~stdout~ (标准输出)作为该参数

    与 ~puts()~ 不同, ~fputs()~ *不会* 在输出的末尾添加换行符

    *注意*: ~gets()~ 丢弃输入中的换行符, 但是 ~puts()~ 在输出中添加换行符.
     ~fgets()~ 保留输入中的换行符, ~fputs()~ 不会在输入中添加换行符.

     假设要写一个循环, 读取一行输入, 另起一行打印该输入:
     #+begin_src c
       char line[81];

       while (gets(line)) {
         puts(line);
       }
     #+end_src

     如果 ~gets()~ 读到文件末尾会返回空指针. 对空指针求值为 0(即为假), 这样便可
     结束循环. 亦可这样写:
     #+begin_src c
       char line[81];

       while (fgets(line, 81, stdin)) {
         fputs(line, stdout);
       }
     #+end_src

     第一个循环, line 数组中的字符串也显示在下一行, 因为 ~fgets()~ 把换行符储存在
     字符串末尾. 注意, 如果混合使用 ~fgets()~ 输入和 ~puts()~ 输出, 每个待显示的
     字符串末尾就会有 2 个换行符. 这里关键要注意: ~puts()~ 应与 ~gets()~ 配对使用,
     ~fputs()~ 应与 ~fgets()~ 配对使用

*** ~printf()~ 函数
    ~printf()~ 也是把字符串的地址作为参数, 虽然没有 ~puts()~ 方便, 但是可以格式
    化不同的数据类型

    ~printf()~ 不会自动在每个字符串末尾上加上一个换行符

** 自定义输入/输出函数
   
   可以在 ~getchar()~ 和 ~putchar()~ 的基础上自定义所需的函数
   
** 字符串函数
   C 提供了多个处理字符串的函数, ANSI C 把这些函数的原型放在 ~string.h~ 头文件中.
   其中最常用的函数有 ~strlen()~, ~strcat()~, ~strcmp()~, ~strcpy()~, 和
   ~strncpy()~. 另外, 还有 ~sprintf()~ 函数, 其原型在 ~stdio.h~ 头文件中.

*** ~strlen()~ 函数
    ~strlen()~ 函数用于统计字符串的长度

*** ~strcat()~ 函数
    ~strcat()~ 函数接受 2 个字符串作为参数. 该函数把第二个字符串的备份附加在第一个
    字符串末尾, 并把拼接后形成的字符串作为第一个字符串, 第二个字符串不变.
    ~strcat()~ 函数的类型是 ~char *~, ~strcat()~ 函数返回第一个参数, 即拼接第二
    个字符串后的第一个字符串的地址

*** ~strncat()~ 函数
    ~strcat()~ 函数无法检查第一个数组是否能容纳第二个字符串. 如果分配给第一个数
    组的空间不够大, 多出来的字符串溢出相邻存储单元时就会出问题. 可使用
    ~strlen()~ 检测, 也可以使用 ~strncat()~, 该函数的第三个参数指定了最大添加字
    符数.

    C11 标准废弃 ~gets()~ 而不废弃 ~strcat()~ 的原因: ~gets()~ 造成的安全隐患来
    自于使用该程序的人, 而 ~strcat()~ 暴露的问题是由程序员造成的. C 语言相信程序
    员

*** ~strcmp()~ 函数
    ~strcmp()~ 比较所有的字符, 不只是字母. 所以, 与其说是该函数按字母顺序进行比
    较, 比如说时机器排序排列(machine collating sequence)进行比较, 即根据字符的数
    值进行比较(通常都使用 ASCⅡ值). 在 ASCⅡ中, 大写字母在小写字母前面, 所以
    ~strcmp("Z", "a")~ 返回的是负值

    大多情况下, 我们仅需返回值是否为 0

    *注意*: ~strcmp()~ 函数比较的是字符串, 不是字符, 所以其参数应该是字符串, 而
     不是字符. 但是, ~char~ 类型实际上是整数类型, 所以可以使用关系运算符来比较字
     符.

     尽管如此, 不要使用字符作为 ~strcmp()~ 的参数

*** ~strncmp()~ 函数
    ~strcmp()~ 函数比较字符串中的字符, 直到发现不同的字符为止, 这一过程可能会持
    续到字符串的末尾. 而 ~strncmp()~ 函数在比较 2 个字符串时, 可以比较到字符不同的
    地方, 也可以只比较第三个参数指定的字符数. 例如, 要查找 ~"astro"~ 开头的字符
    串, 可以限定函数只查找这 5 个字符

*** ~strcpy()~ 和 ~strncpy()~ 函数
    前面提到过, 如果 ~pts1~ 和 ~pts2~ 都是指向字符串的指针, name下面拷贝的是字符
    串的地址而不是字符串本身:
    #+begin_src c
      pts2 = pts1;
    #+end_src

    如果希望拷贝整个字符串, 要使用 ~strcpy()~ 函数.

    ~strcpy()~ 接受2个字符串指针作为参数, 可以把指向源字符串的第二个指针声明为指
    针, 数组名或字符串常量; 而指向源字符串副本的第一个指针应该指向一个 *数据对象
    (如: 数组)*, 且该对象有足够的空间储存源字符串的副本. 
    
    声明数组将分配储存数据的空间, 而声明指针只分配储存一个地址的空间

**** ~strcpy()~ 的其他属性
     ~strcpy()~ 函数还有2个有用的属性:
     1. ~strcpy()~ 函数的返回类型是 ~char *~, 该函数返回的是第一个参数的值, 即一
        个字符的地址.
     2. 第一个参数不必指向数组的开始. 这个属性可用于拷贝数组的一部分

        
     *注意*: ~strcpy()~ 把源字符串中的空字符也拷贝在内

**** 更谨慎的选择: ~strncpy()~
     ~strcpy()~ 和 ~strcat()~ 都有同样的问题, 它们都不能检查目标空间是否能容纳源
     字符串的副本. 拷贝字符串用 ~strncpy()~ 更安全, 第三个参数指明可拷贝的最大字
     符数
     
     ~strncpy(target, source, n)~ 把 ~source~ 中的 ~n~ 个字符或空字符之前的字符
     (*先满足哪个条件就拷贝到何处*)拷贝至 ~target~ 中. 因此, 如果 ~source~ 中的字
     符数小于 ~n~, 如果拷贝到第 ~n~ 个字符时还未拷贝完成整改源字符串, 就不会拷贝
     空字符. 所以, 拷贝的部分中 *不一定* 有空字符. 鉴于此, 该程序(~copy3.c~)就把
     ~n~ 设置为比目标数组的大小少1(TARGSIZE - 1), 然后把数组最后一个元素设置空字
     符:

     #+begin_src c
       strncpy(qwords[i], temp, TARGSIZE - 1);
       qwords[i][TARGSIZE - 1] = '\0';
     #+end_src

     这样做确保储存的是一个字符串. 如果目标空间能容纳字符串的副本, 那么从源字符
     串拷贝的空字符串便是该副本的结尾; 如果目标空间装不下副本, 则把副本最后一个
     元素设置为空字符

*** ~sprintf()~ 函数的返回类型是
    ~sprintf()~ 函数声明在 ~stdio.h~ 中, 而不是在 ~string.h~ 中. 该函数和
    ~printf()~ 类似, 但是它是把数据写入字符串, 而不是打印在显示器上. 因此, 该函
    数可以把多个元素组合成一个字符串. ~sprintf()~ 的第一个参数是目标字符串的地址.
    其余参数和 ~printf()~ 相同, 即格式字符串和待写入项的列表

    ~sprintf()~ 函数获取输入, 并将其格式化为标准形式, 然后把格式化后的字符串储存
    在 ~formal~ 中(见 ~format.c~)

** 其他字符串函数
   ANSI C库有20多个用于处理字符串的函数

   第五章讨论过, ~size_t~ 类型是 ~sizeof~ 运算符返回的类型. C规定 ~sizeof~ 运算
   符返回一个整数类型, 但是并未指定是哪种整数类型, 所以 ~size_t~ 在一个系统中可
   以是 ~unsigned int~, 而在另一个系统中可以是 ~unsigned long~. ~string.h~ 头文
   件针对特定系统定义了 ~size_t~, 或者参考其他有 size_t定义的头文件

   可以用  ~strchr()~ 代替 ~s_gets()~ (自己定义的函数). 首先, 使用 ~strchr()~ 查
   找换行符(如果有). 如果该函数发现了换行符, 将返回该换行符的地址, 然后便可用空
   字符替换该位置上的换行符:

   #+begin_src c
     char line[80];
     char* find;

     fgets(line, 80, stdin);

     find = strchr(line, '\n'); // 查找换行符

     // 如果没有找到换行符, 返回 NULL
     if (find)
       // 把该处的字符替换为空字符
       *find = '\0';
   #+end_src

   如果 ~strchr()~ 未找到换行符, ~fgets()~ 在达到行末尾之前就达到了它能读取的最
   大字符数. 可以像在 ~s_gets()~ 中那样, 给 if 添加一个 else 来处理这种情况.
** 字符串示例: 字符串排序(~sort_str.c~)
   处理一个按字母表排序字符串的实际问题. 准备名单表, 创建索引和许多其他情况下都
   会用到字符串排序. 该程序主要是用 ~strcmp()~ 函数来确定2个字符串的顺序. 一般的
   做法是读取字符串函数, 偶爱徐字符串并打印出来.

*** 排序指针而非字符串
    该程序的巧妙之处在于排序的是指向字符串的指针, 而不是字符串本身.
    如果按字母排序 ~input[1]~ 在 ~input[0]~ 前面, 程序便交换指向它们的指针

    这样做比用 ~strcpy()~ 交换2个 ~input~ 字符串的内容简单得多, 而且还保留了原始
    数据


*** 选择排序算法
    利用 ~for~ 循环以此把每个元素与首元素比较. 如果待比较的元素在当前首元素的前
    面, 则交换两者. 循环结束时, 首元素包含的指针指向机器排序序列最考勤的字符串.
    然后外层 ~for~ 循环重复这一过程, 这次从 ~input~ 的第二个元素开始. 当内层循环
    执行完毕时, ~ptrst~ 中的第二个元素指向排在第二个字符串. 这一过程持续到所有元
    素都已排序完毕

    C库中还有一个更高级的排序函数: ~qsort()~. 该函数使用一个指向函数的指针进行排
    序比较, 将在第16章给出该函数的用法示例

** ~ctype.h~ 字符函数和字符串
   第7章介绍了 ~ctype.h~ 系列与字符相关的函数, 虽然这些函数不能处理整个字符串,
   但是可以处理字符串中的字符.

   顺带一提, ~ctype.h~ 中的函数通常作为宏(macro)来实现. 这些C预处理器宏的作用很
   像函数, 但是两者有一些重要的区别. 在16章再讨论关于宏的内容.

   该程序使用 ~fgets()~ 和 ~strchr()~ 组合, 读取一行输入并把换行符替换成空字符.
   这种方法与使用 ~s_gets()~ 的区别是: ~s_gets()~ 会处理输入行剩余字符(如果有),
   为下一次输入做准备. 本例中仅有1条语句, 没必要进行多余步骤
